feat: add new link 'Tilgjenglighetserklæring' to footer
fellesdatakatalog/fdk-kit pull request #201
Opened 2023-01-29 13:31 UTC by hegeaal

2023-01-29 20:15 UTC, jeffreiffers requested changes

2023-01-29 20:15 UTC, jeffreiffers commented on packages/external-footer/src/utils/localization/en.ts
> +  accessibility: "Accessability",
```suggestion
  accessibility: "Accessibility",
```

2023-01-30 12:27 UTC, hegeaal commented on packages/external-footer/src/utils/localization/en.ts
> +  accessibility: "Accessability",
Fikset 👆

2023-01-30 14:49 UTC, jeffreiffers approved these changes

2023-01-30 15:06 UTC, merged