Add expansion panel
fellesdatakatalog/fdk-kit pull request #23
Opened 2021-04-13 06:47 UTC by oyvindis

2021-04-13 11:07 UTC, azaxarov requested changes

2021-04-13 11:07 UTC, azaxarov commented on packages/expansion-panel/src/components/expansion-panel-head/index.tsx
> +export const ExpansionPanelHead: FC<any> = ({ children }) => children;
Bare for at props er litt mer ryddig:

```suggestion
import type { FC, PropsWithChildren } from 'react';

interface Props {}

export const ExpansionPanelHead: FC<PropsWithChildren<Props>> = ({ children }) => children;
```

2021-04-13 11:07 UTC, azaxarov commented on packages/expansion-panel/src/components/expansion-panel/index.tsx
> +  collapse: JSX.Element;
Kanskje ReactNode (import fra`react`) passer bedre?

```suggestion
  expand: ReactNode;
  collapse: ReactNode;
```

2021-04-13 11:07 UTC, azaxarov commented on packages/expansion-panel/src/components/expansion-panel/index.tsx
> +    )?.shift();
Deler av koden kan flyttes til `utils.ts`. Se gjerne https://github.com/fellesdatakatalog/fdk-kit/blob/master/packages/tabs/src/components/tabs/utils.ts for inspirasjonen

2021-04-14 09:29 UTC, oyvindis commented on packages/expansion-panel/package.json
> +{
Mente du package-lock? Hvis jeg fjerner package.json mister vel "version" og ikke kan ha den i stories.mdx?

2021-04-14 09:29 UTC, oyvindis commented on packages/expansion-panel/stories/expansion.stories.mdx
> +import {
Oppdaterer .editorconfig til å ta med .mdx

2021-04-14 09:33 UTC, oyvindis commented on packages/expansion-panel/src/components/expansion-panel-body/index.tsx
> +export const ExpansionPanelBody: FC<any> = ({ children }) => children;
Endret til å ha med PropsWithChildren , men er rart at den ikke liker FC<PropsWithChildren<Props>>, men FC<PropsWithChildren<any>> går fint.

2021-04-14 09:47 UTC, azaxarov approved these changes
Nice!

2021-04-14 09:57 UTC, azaxarov commented on packages/expansion-panel/package.json
> +{
Ja, package-lock skal bort

2021-04-16 06:54 UTC, merged